name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-node@v3.6.0
      - run: |
          npm install
          npm run docs
          npm run docs:json

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: docs
          force_orphan: true
          commit_message: 'docs: update'
