name: Release

on:
  push:
    branches:
      - main
      - next
      - rc
  workflow_dispatch:

permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up Node
        uses: actions/setup-node@v3.6.0
      - run: |
          npm install
          npm run build

      - uses: cycjimmy/semantic-release-action@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
